name: Run Python Bot

on:
  push:
    branches: ["main"]      # jab main branch pe push hoga
  workflow_dispatch:        # manually run karne ka option Actions tab me
  schedule:                 # auto restart
    - cron: "0 */6 * * *"   # har 6 ghante me dobara run hoga (UTC time)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Show environment info   # 🟢 system + Python details
      run: |
        echo "=== Python Version ==="
        python --version
        echo "=== Path ==="
        which python
        echo "=== Installed packages ==="
        pip list

    - name: Show all environment variables  # 🟢 background env dekhne ke liye
      run: |
        echo "=== ENVIRONMENT VARIABLES ==="
        env

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run bot (with debug logs)
      run: |
        echo "=== Running main.py ==="
        python -u main.py
